// <auto-generated />
namespace Magic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class deckthings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deckthings));
        
        string IMigrationMetadata.Id
        {
            get { return "201311141607132_deckthings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
