// <auto-generated />
namespace Magic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class CHatRoom_ApplicationUserConnection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CHatRoom_ApplicationUserConnection));
        
        string IMigrationMetadata.Id
        {
            get { return "201406261641188_CHatRoom_ApplicationUserConnection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
