src="~/Scripts/jquery.signalR-2.0.0.min.js"
//Reference the autogenerated SignalR hub script.
src="~/signalr/hubs"

        $(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = $.connection.chatHub;
            // Set initial focus to message input box.
            // $('#message').focus();
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#chat-send').click(function () {
                    alert("Okey dokey!");
                    // Call the Send method on the hub.
                    chat.server.send(Model);
                    // Clear text box and reset focus for next comment.
                    $('#chat-message').val(''); //.focus();
                });
            });
        });

        // Create a function that the hub can call back to display messages.
        chat.client.addNewMessageToPage = function (time, name, message) {
            // Add the message to the page.
            $('#discussion').append('<li>' + time + '<strong>' + htmlEncode(name)
                + '</strong>: ' + htmlEncode(message) + '</li>');
        };

// This optional function html-encodes messages for display in the page.
function htmlEncode(value) {
    var encodedValue = $('<div />').text(value).html();
    return encodedValue;
}